### ISSUE TITLE
Trying clone then use just Edge Detection

### ISSUE THREAD

**Issue by madisonflaget** [kylemcdonald/cv-examples#1]
I am trying to incorporate Edge Detection into one of my sketches but it won't load properly. I suspect it has to do with the shared/utils.js file that is mentioned in the read me. It says you may have issues running one sketch, but offers no solutions. I fully intend to modify the code and give proper credit, but just need to get the code copied and working first. Can I get some help getting it going?

My code is published publicly on Github at: https://github.com/madisonflaget/440-work/tree/master/Project_2/edge_detection_base

**Comment by kylemcdonald** [comment]
Hi, it looks like you figured it out since submitting this issue? If not, please post a copy of the error message.
